package daycare.models;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;
import org.junit.jupiter.api.Test;

class PetTest {

  static class TestPet extends Pet {
    TestPet(String name, int age, Owner owner, int id) {
      super(name, age, owner, id);
    }
    @Override public double calculateWeeklyFee() { return 0; }
  }

  @Test void constructorAssignsFields() {
    Owner alice = new Owner(1, "Alice", "", "", "");
    Pet p = new TestPet("Rex", 3, alice, 0);
    assertEquals("Rex", p.getName());
    assertEquals(3, p.getAge());
    assertSame(alice, p.getOwner());
    assertTrue(p.getId() >= Pet.FIRST_ID);
  }

  @Test void explicitIdAtOrAboveFirstIdIsKept() {
    Pet p = new TestPet("A", 1, null, 5000);
    assertEquals(5000, p.getId());
  }

  @Test void explicitIdBelowFirstIdGetsAutoGenerated() {
    Pet p = new TestPet("A", 1, null, 5);
    assertTrue(p.getId() >= Pet.FIRST_ID);
  }

  @Test void nameLongerThanMaxGetsTruncated() {
    String longName = "x".repeat(Pet.MAX_NAME_LENGTH + 10);
    Pet p = new TestPet(longName, 1, null, 0);
    assertEquals(Pet.MAX_NAME_LENGTH, p.getName().length());
  }

  @Test void setNameUpdatesAndTruncates() {
    Pet p = new TestPet("old", 1, null, 0);
    p.setName("x".repeat(50));
    assertEquals(Pet.MAX_NAME_LENGTH, p.getName().length());
  }

  @Test void setNameIgnoresNull() {
    Pet p = new TestPet("orig", 1, null, 0);
    p.setName(null);
    assertEquals("orig", p.getName());
  }

  @Test void initNameMatchesSetName() {
    Pet p = new TestPet("orig", 1, null, 0);
    p.initName("new");
    assertEquals("new", p.getName());
    p.initName(null);
    assertEquals("new", p.getName());
  }

  @Test void setAgeAlwaysUpdates() {
    Pet p = new TestPet("x", 1, null, 0);
    p.setAge(10);
    assertEquals(10, p.getAge());
  }

  @Test void setOwnerIgnoresNull() {
    Owner o = new Owner(1, "Alice", "", "", "");
    Pet p = new TestPet("x", 1, o, 0);
    p.setOwner(null);
    assertSame(o, p.getOwner());
  }

  @Test void setOwnerUpdatesOnValid() {
    Pet p = new TestPet("x", 1, null, 0);
    Owner o = new Owner(1, "Alice", "", "", "");
    p.setOwner(o);
    assertSame(o, p.getOwner());
  }

  @Test void daysAttendingDefaultsToAllFalse() {
    Pet p = new TestPet("x", 1, null, 0);
    for (boolean day : p.getDaysAttending()) {
      assertFalse(day);
    }
    assertEquals(0, p.numOfDaysAttending());
  }

  @Test void checkInValidDaysMarksAttending() {
    Pet p = new TestPet("x", 1, null, 0);
    p.checkIn(0);
    p.checkIn(5);
    assertTrue(p.getDaysAttending()[0]);
    assertTrue(p.getDaysAttending()[5]);
    assertEquals(2, p.numOfDaysAttending());
  }

  @Test void checkInInvalidDaysIgnored() {
    Pet p = new TestPet("x", 1, null, 0);
    p.checkIn(-1);
    p.checkIn(6);
    p.checkIn(100);
    assertEquals(0, p.numOfDaysAttending());
  }

  @Test void checkOutClearsAttendance() {
    Pet p = new TestPet("x", 1, null, 0);
    p.checkIn(2);
    p.checkOut(2);
    assertFalse(p.getDaysAttending()[2]);
  }

  @Test void checkOutInvalidDaysIgnored() {
    Pet p = new TestPet("x", 1, null, 0);
    p.checkIn(0);
    p.checkOut(-1);
    p.checkOut(100);
    assertEquals(1, p.numOfDaysAttending());
  }

  @Test void getDaysAttendingReturnsDefensiveCopy() {
    Pet p = new TestPet("x", 1, null, 0);
    boolean[] got = p.getDaysAttending();
    got[0] = true;
    assertFalse(p.getDaysAttending()[0]);
  }

  @Test void setDaysAttendingCopiesValidArray() {
    Pet p = new TestPet("x", 1, null, 0);
    boolean[] sched = new boolean[Pet.DAYS_PER_WEEK];
    sched[1] = true;
    p.setDaysAttending(sched);
    sched[2] = true;
    assertEquals(1, p.numOfDaysAttending());
  }

  @Test void setDaysAttendingIgnoresWrongLength() {
    Pet p = new TestPet("x", 1, null, 0);
    p.setDaysAttending(new boolean[3]);
    assertEquals(Pet.DAYS_PER_WEEK, p.getDaysAttending().length);
  }

  @Test void setDaysAttendingIgnoresNull() {
    Pet p = new TestPet("x", 1, null, 0);
    p.setDaysAttending(null);
    assertNotNull(p.getDaysAttending());
  }

  @Test void setIdOverwrites() {
    Pet p = new TestPet("x", 1, null, 0);
    p.setId(9999);
    assertEquals(9999, p.getId());
  }

  @Test void toStringContainsKeyFields() {
    Owner o = new Owner(1, "Alice", "", "", "");
    Pet p = new TestPet("Rex", 3, o, 0);
    String s = p.toString();
    assertTrue(s.contains("Rex"));
    assertTrue(s.contains("Alice"));
  }

  @Test void toStringHandlesNullOwner() {
    Pet p = new TestPet("Rex", 3, null, 0);
    assertTrue(p.toString().contains("none"));
  }

  @Test void chaos_emptyNameAllowed() {
    Pet p = new TestPet("", 1, null, 0);
    assertEquals("", p.getName());
  }

  @Test void chaos_nullNameTruncatesToNull() {
    Pet p = new TestPet(null, 1, null, 0);
    assertNull(p.getName());
  }

  @Test void chaos_negativeAgeStored() {
    Pet p = new TestPet("x", -5, null, 0);
    assertEquals(-5, p.getAge());
  }

  @Test void chaos_massiveExplicitIdBumpsCounter() {
    new TestPet("x", 1, null, 5_000_000);
    Pet next = new TestPet("y", 1, null, 0);
    assertTrue(next.getId() > 5_000_000);
  }

  @Test void chaos_recomputeNextIdAdvancesCounter() {
    Pet.recomputeNextId(List.of(new TestPet("a", 1, null, 9_000_000)));
    Pet next = new TestPet("b", 1, null, 0);
    assertTrue(next.getId() > 9_000_000);
  }

  @Test void chaos_recomputeNextIdNullIsNoop() {
    Pet.recomputeNextId(null);
  }

  @Test void chaos_recomputeNextIdIgnoresNullEntries() {
    Pet.recomputeNextId(java.util.Arrays.asList(null, null));
  }

  @Test void chaos_nameAtExactMaxStaysIntact() {
    String exact = "x".repeat(Pet.MAX_NAME_LENGTH);
    Pet p = new TestPet(exact, 1, null, 0);
    assertEquals(exact, p.getName());
  }

  @Test void chaos_doubleCheckInIdempotent() {
    Pet p = new TestPet("x", 1, null, 0);
    p.checkIn(3);
    p.checkIn(3);
    assertEquals(1, p.numOfDaysAttending());
  }

  @Test void chaos_checkOutWithoutCheckInIsFine() {
    Pet p = new TestPet("x", 1, null, 0);
    p.checkOut(3);
    assertEquals(0, p.numOfDaysAttending());
  }
}
